/*
 * Copyright (c) 2017 Intel Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if !defined(CONFIG_CPU_CORTEX_M)
  #error project can only run on Cortex-M
#endif

#include <ztest.h>
#include "dfe_samples_mapping_test.h"
#include "configuration_fixtures.h"
#include "dfe_configuration_tests.h"

void test_main(void)
{
	ztest_test_suite(sampling_type_tests,
		ztest_unit_test_setup_teardown(test_sampling_type_when_oversampling_configured, setup_fixture_prepare_over_sampling, common_teardown),
		ztest_unit_test_setup_teardown(test_sampling_type_when_bt_1us_slot_configured, setup_fixture_prepare_bt_sampling_1us_switch_slot, common_teardown),
		ztest_unit_test_setup_teardown(test_sampling_type_when__bt_2us_slot_configured, setup_fixture_prepare_bt_sampling_2us_switch_slot, common_teardown),
		ztest_unit_test_setup_teardown(test_sampling_type_when_undersampling_configured_ommit_2nd_slot, setup_fixture_prepare_undersampling_sample_every_2nd_slot, common_teardown),
		ztest_unit_test_setup_teardown(test_sampling_type_when_undersampling_configured_ommit_4nd_slot, setup_fixture_prepare_undersampling_sample_every_4th_slot, common_teardown));

	ztest_test_suite(calculation_of_effective_slots_tests,
		ztest_unit_test_setup_teardown(test_calculation_of_effective_slots_number_for_oversampling, setup_fixture_prepare_over_sampling, common_teardown),
		ztest_unit_test_setup_teardown(test_calculation_of_effective_slots_number_for_ble_1us_slot, setup_fixture_prepare_bt_sampling_1us_switch_slot, common_teardown),
		ztest_unit_test_setup_teardown(test_calculation_of_effective_slots_number_for_ble_2us_slot, setup_fixture_prepare_bt_sampling_2us_switch_slot, common_teardown),
		ztest_unit_test_setup_teardown(test_calculation_of_effective_slots_number_for_under_sampling, setup_fixture_prepare_undersampling_sample_every_2nd_slot, common_teardown),
		ztest_unit_test_setup_teardown(test_calculation_of_effective_slots_number_for_under_sampling, setup_fixture_prepare_undersampling_sample_every_4th_slot, common_teardown));

	ztest_test_suite(test_iq_samples_and_antenna_mapping,
		ztest_unit_test_setup_teardown(test_iq_samples_to_ant_mapping_if_oversampling_configured, setup_fixture_prepare_iq_data_and_over_sampling_config, common_teardown),
		ztest_unit_test_setup_teardown(test_iq_samples_to_ant_mapping_if_ble_compliant_sampling_is_configured, setup_fixture_prepare_bt_sampling_1us_switch_slot, common_teardown),
		ztest_unit_test_setup_teardown(test_iq_samples_to_ant_mapping_if_ble_compliant_sampling_is_configured, setup_fixture_prepare_bt_sampling_2us_switch_slot, common_teardown),
		ztest_unit_test_setup_teardown(test_iq_samples_to_ant_mapping_if_undersampling_is_configured, setup_fixture_prepare_undersampling_sample_every_2nd_slot, common_teardown),
		ztest_unit_test_setup_teardown(test_iq_samples_to_ant_mapping_if_undersampling_is_configured, setup_fixture_prepare_undersampling_sample_every_4th_slot, common_teardown));

	ztest_test_suite(test_remove_samples_from_switching_slots,
		ztest_unit_test_setup_teardown(test_remove_samples_from_switching_slots_every_2nd_slot_to_remove, setup_fixture_prepare_over_sampling, common_teardown),
		ztest_unit_test_setup_teardown(test_remove_samples_from_switching_slots_all_slots_to_remove, setup_fixture_prepare_over_sampling, common_teardown),
		ztest_unit_test_setup_teardown(test_remove_samples_from_switching_slots_no_slot_to_remove, setup_fixture_prepare_over_sampling, common_teardown));


	ztest_run_test_suite(sampling_type_tests);
	ztest_run_test_suite(calculation_of_effective_slots_tests);
	ztest_run_test_suite(test_iq_samples_and_antenna_mapping);
	ztest_run_test_suite(test_remove_samples_from_switching_slots);
}
